# Generated by Django 4.0.1 on 2022-01-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='method',
            field=models.CharField(default='GET', max_length=100),
        ),
    ]
