# Generated by Django 4.0.1 on 2022-01-30 19:51

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_request_body_alter_request_header_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='server',
        ),
        migrations.AlterField(
            model_name='request',
            name='body',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='header',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False),
        ),
    ]
