# Generated by Django 4.0.1 on 2022-01-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_remove_request_server_alter_request_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
