# Generated by Django 4.0.1 on 2022-01-31 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_remove_request_header_alter_request_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='requests',
        ),
    ]
