# Generated by Django 4.0.1 on 2022-01-31 12:01

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_remove_server_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='header',
            field=picklefield.fields.PickledObjectField(default={}, editable=False),
        ),
        migrations.AddField(
            model_name='request',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='body',
            field=picklefield.fields.PickledObjectField(default={}, editable=False),
        ),
    ]
