# Generated by Django 4.0.1 on 2022-01-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_request_header_request_url_alter_request_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='body',
            field=models.CharField(default='{}', max_length=10000),
        ),
        migrations.AlterField(
            model_name='request',
            name='header',
            field=models.CharField(default='{}', max_length=10000),
        ),
    ]
