# Generated by Django 4.0.1 on 2022-01-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_alter_request_body_alter_request_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='body',
        ),
        migrations.RemoveField(
            model_name='request',
            name='handled',
        ),
        migrations.RemoveField(
            model_name='request',
            name='header',
        ),
    ]
