# Generated by Django 4.0.1 on 2022-01-31 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0011_request_body_request_header_request_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='url',
            new_name='address',
        ),
    ]
