# Generated by Django 4.0.1 on 2022-01-31 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0012_rename_url_request_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='address',
            new_name='servers',
        ),
    ]
