# Generated by Django 4.0.1 on 2022-01-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0013_rename_address_request_servers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='servers',
            new_name='server',
        ),
    ]
