# Generated by Django 4.0.1 on 2022-02-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0014_rename_servers_request_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
    ]
